### ISSUE TITLE
Suggestion: Add Instagram feed

### ISSUE THREAD

**Issue by BestGamer** [FRC-4121/FRC-4121.github.io#12]
Add Instagram feed on the contact us page just like the twitter feed.

**Comment by realadamplayer** [comment]
Can't seem to find a embed for instagram sadly, though I feel like there's one out there.

**Comment by BestGamer** [comment]
found one on wordpress
https://wordpress.org/plugins/instagram-feed/

**Comment by realadamplayer** [comment]
We don't use wordpress.

**Comment by BestGamer** [comment]
its a plugin u can download it doesnt require wordpress

**Comment by BestGamer** [comment]
this was other thing i found
http://instafeedjs.com/

also found jquery plugin socialist
http://plugins.jquery.com/socialist/

**Comment by realadamplayer** [comment]
I think using the instagram API and tailoring it to our website itself would be better than relying on a plugin to do it for us.
