### ISSUE TITLE
menu bar triggering to early / to late on home page

### ISSUE THREAD

**Issue by BestGamer** [FRC-4121/FRC-4121.github.io#6]
When triggered late : cant read when its over the orange text 
When triggered early : triggering while inside jumbotron
- Depends on screen size because triggers on top of text when in dev mode with responsive mode enabled
- Only on home page
- on pages other than home it triggers as soon as you scroll (only confirmed on contact us page since its only page you can scroll on besides home)

**Comment by realadamplayer** [comment]
Probably has something to do with the calculation of the height of which the navbar switches classes. The height of the navbar is either 25, which is what is reported in the js below, or 50, which I think I put in the less files for the css.

Navbar fade script

```
    $(function() {
        $(window).scroll(function() {
            var scroll = $(window).scrollTop();
            if(scroll >= ( $('.jumbotron').height() + 25 )){ // Takes the height of the jumbotron and adds 25, which is the height of the navbar
                $('.navbar').removeClass("clearnav").addClass('solidnav');
                } else {
                $('.navbar').removeClass('solidnav').addClass('clearnav');
            };
        });
    });
```

**Comment by realadamplayer** [comment]
Fix'd it by hard coding in the padding size for jumbotrons, which is 11.6 em (~350px). The navbar now switches classes when it's very close to the actual content row.
